### ISSUE TITLE
allow video stickers

### ISSUE THREAD

**Issue by LuckyTurtleDev** [LuckyTurtleDev/mstickereditor#16]
need to convert webm to webp

**Comment by LuckyTurtleDev** [comment]
This should be possible with the [matroska-demuxer](https://crates.io/crates/matroska-demuxer) and the [image](https://crates.io/crates/image) crate. Alternative instead of image the [webp-animation](https://crates.io/crates/webp-animation/0.7.0) can be used to avoid hassle with c dependencys (lotticonf and image use both libwebp). 

@msrd0  what was the advance of the webp-animation over the image crate?

**Comment by msrd0** [comment]
Iirc, at the time of choosing that library, the `image` crate did not support animated webp. no idea if this has changed since then.

**Comment by msrd0** [comment]
And `lottieconv` uses `webp-animation`, not libwebp

**Comment by LuckyTurtleDev** [comment]
> And `lottieconv` uses `webp-animation`, not libwebp

but `web-animation` use `libwebp-sys2`

**Comment by msrd0** [comment]
Nvm, `webp-animation` also relies on the C library, so it looks like we cannot avoid the c dependency. Also we will always have a dependency on the rlottie C library.

**Comment by LuckyTurtleDev** [comment]
looks like the image crate. Is currently working on a pure rust webp decoder. see https://github.com/image-rs/image/issues/1984

However it sounds like they will still depend on the c lib. :disappointed: 

> Note: regardless of changes to the image crate, the webp crate will continue to provide Rust bindings to libwebp.

**Comment by LuckyTurtleDev** [comment]
Feature will be available at the next release
