### ISSUE TITLE
How to run mstickereditor?

### ISSUE THREAD

**Issue by PtPhoenix** [LuckyTurtleDev/mstickereditor#27]
I'm sorry for the stupid question, but I can't run it. How to use it? If I just run 'mstickereditor' terminal it won't work.
I use Garuda linux. I pre-installed sticker-picker.

**Comment by msrd0** [comment]
You can install this project from the AUR for all ArchLinux-based distros: https://aur.archlinux.org/packages?O=0&K=mstickereditor

Then, you can just run `mstickereditor` from your terminal emulator of choice.

**Comment by PtPhoenix** [comment]
> 

I don't know why it didn't work with cargo. I was so confused because I needed to install dependencies and I forgot that I should use AUR. Thank you. It works

**Comment by LuckyTurtleDev** [comment]
@PtPhoenix  Make sure that `~/.cargo/bin` is listed in the `PATH` environment variable if you install something with cargo install.

**Comment by LuckyTurtleDev** [comment]
TODO:

- [ ] clarify install with cargo
- [ ] add repology badges
