### ISSUE TITLE
Stickers don't show up on Element desktop

### ISSUE THREAD

**Issue by PtPhoenix** [LuckyTurtleDev/mstickereditor#28]
Animated stickers don't show up on github page too, but somehow work just fine on SchildiChat on Android. I previously used sticker picker to import Telegram sticker packs. After using mstickereditor I changed index.json and added other json files. 

Am I doing something wrong?

**Comment by LuckyTurtleDev** [comment]
Have you deleted the cache of element? Sometimes the old picker is still cached.

**Comment by PtPhoenix** [comment]
Yeah. Didn't help. I uploaded more and a few of them showed up on github page and now everywhere it's the same. Not all of them are showing up

**Comment by LuckyTurtleDev** [comment]
You probably need to reload the picker after adding more sticker after adding new.
[maunium/stickerpicker](https://github.com/maunium/stickerpicker), [msrdo/docker-stickerpicker](https://github.com/msrd0/docker-stickerpicker) as well as [LuckyTurtleDev/mstickerpicker](https://github.com/LuckyTurtleDev/mstickerpicker) provide a reload button at the bottom for this.

Which picker did you use at all?

**Comment by PtPhoenix** [comment]
I use [maunium/stickerpicker](https://github.com/maunium/stickerpicker), widget with [LuckyTurtleDev/mstickerpicker](https://github.com/LuckyTurtleDev/mstickerpicker).  I found the button in [maunium/stickerpicker](https://github.com/maunium/stickerpicker), but pressing it did nothing. Not even on github page

**Comment by PtPhoenix** [comment]
I'm only importing and converting with mstickereditor and importing from Telegram. And hosting fork of stickerpicker on github pages.

**Comment by LuckyTurtleDev** [comment]
If I open your picker I get the folllowing error:
```
Uncaught (in promise) TypeError: pack.stickers[0] is undefined
    NavBarItem https://ptphoenix.github.io/stickerpicker/web/src/index.js:339
    Preact 16
    _loadPacks https://ptphoenix.github.io/stickerpicker/web/src/index.js:179
    _loadPacks https://ptphoenix.github.io/stickerpicker/web/src/index.js:157
    componentDidMount https://ptphoenix.github.io/stickerpicker/web/src/index.js:190
    Preact 4
    <anonymous> https://ptphoenix.github.io/stickerpicker/web/src/index.js:363
index.js:339:1
```
This is occurs at this line:
```
<img src=${makeThumbnailURL(pack.stickers[0].url)}
					alt=${pack.stickers[0].body} class="visible" />
```
This sounds like you are using a pack with 0 stickers, which cause the [maunium/stickerpicker](https://github.com/maunium/stickerpicker) to fail. After this error the picker stop to load the remaining packs. You should remove the pack and probably report this issue to [maunium/stickerpicker](https://github.com/maunium/stickerpicker).

**Comment by LuckyTurtleDev** [comment]
@PtPhoenix  can this be closed now?

**Comment by PtPhoenix** [comment]
You mean mp4 file can be converted too now?
