### ISSUE TITLE
Pull requests do not have acces to TG_BOT_KEY

### ISSUE THREAD

**Issue by LuckyTurtleDev** [LuckyTurtleDev/mstickereditor#43]
Pull requests do not have access to TG_BOT_KEY. This let the ci fail on them.

Happen in #42

**Comment by msrd0** [comment]
Do you want pull requests to be able to extract the tg bot key?

It might be better to set up your own proxy that replaces a "dummy" key with the actual key, but only for the one request the ci will make, and never expose the actual key to potentially untrusted workloads.
