### ISSUE TITLE
compiling error on debian bookworm rpi5

### ISSUE THREAD

**Issue by bendschs** [LuckyTurtleDev/mstickereditor#49]
getting the following error message when trying to compile on a raspberry 5 on debian bookworm:

 

> [...]
>    Compiling indexmap v2.2.6
>    Compiling clap v3.2.25
>    Compiling rayon v1.10.0
>    Compiling tempfile v3.10.1
>    Compiling env_logger v0.11.3
>    Compiling sha2 v0.10.8
>    Compiling monostate v0.1.12
>    Compiling strum_macros v0.26.2
>    Compiling flate2 v1.0.28
> error[E0004]: non-exhaustive patterns: `sys::AVPixelFormat::AV_PIX_FMT_SAND128`, `sys::AVPixelFormat::AV_PIX_FMT_SAND64_10`, `sys::AVPixelFormat::AV_PIX_FMT_SAND64_16` and 2 more not covered
>     --> /home/pi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ffmpeg-next-7.0.0/src/util/format/pixel.rs:481:15
>      |
> 481  |         match value {
>      |               ^^^^^ patterns `sys::AVPixelFormat::AV_PIX_FMT_SAND128`, `sys::AVPixelFormat::AV_PIX_FMT_SAND64_10`, `sys::AVPixelFormat::AV_PIX_FMT_SAND64_16` and 2 more not covered
>      |
> note: `sys::AVPixelFormat` defined here
>     --> /tmp/cargo-installNZv5JW/release/build/ffmpeg-sys-next-092633c7ca611632/out/bindings.rs:5627:1
>      |
> 5627 | pub enum AVPixelFormat {
>      | ^^^^^^^^^^^^^^^^^^^^^^
> ...
> 5823 |     AV_PIX_FMT_SAND128 = 194,
>      |     ------------------ not covered
> 5824 |     AV_PIX_FMT_SAND64_10 = 195,
>      |     -------------------- not covered
> 5825 |     AV_PIX_FMT_SAND64_16 = 196,
>      |     -------------------- not covered
> 5826 |     AV_PIX_FMT_RPI4_8 = 197,
>      |     ----------------- not covered
> 5827 |     AV_PIX_FMT_RPI4_10 = 198,
>      |     ------------------ not covered
>      = note: the matched value is of type `sys::AVPixelFormat`
> help: ensure that all possible cases are being handled by adding a match arm with a wildcard pattern as shown, or multiple match arms
>      |
> 778  ~             AV_PIX_FMT_P416LE => Pixel::P416LE,
> 779  ~             _ => todo!(),
>      |
> 
>    Compiling lottieconv v0.3.0
> For more information about this error, try `rustc --explain E0004`.
> error: could not compile `ffmpeg-next` (lib) due to previous error
> warning: build failed, waiting for other jobs to finish...
> error: failed to compile `mstickereditor v0.3.4`, intermediate artifacts can be found at `/tmp/cargo-installNZv5JW`.
> To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

**Comment by msrd0** [comment]
That looks suspiciously like your ffmpeg version isn't supported by [ffmpeg-next](https://crates.io/crates/ffmpeg-next).

**Comment by LuckyTurtleDev** [comment]
@bendschs how @msrd0 has wrote your ffmpeg version is to old. You must wait until debian publish the current version. For the moment you can build it without the ffmpeg feature.

One alternative to forward the `build` feature flag of [ffmpeg-next](https://crates.io/crates/ffmpeg-next) to mstickereditor, so the right ffmpeg version will be automatically build during the build process.

**Comment by bendschs** [comment]
sadly i am not familiar with cargo, how do I execute the respective options?

**Comment by LuckyTurtleDev** [comment]
´´´
cargo install --no-default-features --features lottie mstickereditor
´´´

**Comment by bendschs** [comment]
> The latest release has now a `ffmpeg-build` feauture which download and build the needed ffmpeg version automaticly. But for this some c build tools are needed.
> 
> ```
> cargo install  --features ffmpeg-build mstickereditore
> ```

that actually worked out of the box! thank you!
