### ISSUE TITLE
Consider using lottieconv crate

### ISSUE THREAD

**Issue by msrd0** [LuckyTurtleDev/mstickereditor#8]
The lottie2gif and lottie2webp crates have been deprecated in favor of the new lottieconv crate.

**Comment by msrd0** [comment]
I believe you forgot to call `.convert()` here:

https://github.com/LuckyTurtleDev/mstickereditor/commit/0ec1773d32f5ab24f0d104d0400959a1ecb3a1e2#diff-f25eb935e32c91191b89e1075d6153268d82f6c3a1e703d49f30b7d46bc61b5eR198

**Comment by msrd0** [comment]
The newest version of `lottieconv` includes a warning for such cases:

```
    Checking lottieconv v0.1.2
    Checking mstickereditor v0.2.0 (/home/msrd0/git/mstickereditor)
warning: unused `Converter` that must be used
   --> src/sub_commands/import.rs:197:8
    |
197 | ...                   converter.gif(config.sticker.transparent_color, &mut sticker_image)?;
    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: `#[warn(unused_must_use)]` on by default
    = note: A Converter does nothing unless you call .convert()

warning: `mstickereditor` (bin "mstickereditor") generated 1 warning
```

**Comment by LuckyTurtleDev** [comment]
Thanks for hint.
I am happy that I have not a release that yet.
